//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextReplacer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextReplacer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close File [{0}]..
        /// </summary>
        internal static string infoCloseFile {
            get {
                return ResourceManager.GetString("infoCloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) with extension {1} were found..
        /// </summary>
        internal static string infoCountFiles {
            get {
                return ResourceManager.GetString("infoCountFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file [{0}]..
        /// </summary>
        internal static string infoOpenFile {
            get {
                return ResourceManager.GetString("infoOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Ended. {0} files where edited..
        /// </summary>
        internal static string infoReplaceEnded {
            get {
                return ResourceManager.GetString("infoReplaceEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Started..
        /// </summary>
        internal static string infoReplaceStarted {
            get {
                return ResourceManager.GetString("infoReplaceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace [{0}], with [{1}]..
        /// </summary>
        internal static string infoReplaceValue {
            get {
                return ResourceManager.GetString("infoReplaceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 files with extension {0} were found..
        /// </summary>
        internal static string infoZeroCountFiles {
            get {
                return ResourceManager.GetString("infoZeroCountFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit file [{0}], because the replaced text [{1}] already exist in the content..
        /// </summary>
        internal static string wrnTextExists {
            get {
                return ResourceManager.GetString("wrnTextExists", resourceCulture);
            }
        }
    }
}
